modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="mob_grinding_utils"
version="${file.jarVersion}"
displayName="Mob Grinding Utils"
logoFile="examplemod.png"
credits=""
authors="vadis365, flanks255"
description='''
A mod that adds a fun ways to farm mobs'''
[[dependencies.mob_grinding_utils]]
modId="forge"
mandatory=true
versionRange="[43.3.0,)"
ordering="NONE"
side="BOTH"
