modLoader="javafml"
loaderVersion="[2,)"
license="All rights reserved"
[[mods]]
modId="mob_grinding_utils"
version="${file.jarVersion}"
displayName="Mob Grinding Utils"
logoFile="examplemod.png"
credits=""
authors="vadis365, flanks255"
description='''
A mod that adds a fun ways to farm mobs'''
[[dependencies.mob_grinding_utils]]
modId="neoforge"
required=true
versionRange="[20.4,)"
ordering="NONE"
side="BOTH"
